avoid name conflict with C++17; rel 2
C++17 introduced new symbol "clamp" which conflicts with macro in vsxu's
public header. since projects might request C++17 explicitly or
implicitly (GCC 11 defaults to C++17) disable macro if compiled with
this or higher standard. in case there are users of clamp macro, it
should be either changed to std::clamp or equivalent CLAMP macro. note
there's no need to update vsxu codebase since it uses C++11.

fixes vlc build error:

/usr/include/c++/11.1.0/bits/algorithmfwd.h:229:55: error: macro "clamp" passed 4 arguments, but takes just 3
  229 |     clamp(const _Tp&, const _Tp&, const _Tp&, _Compare);
      |                                                       ^
In file included from /usr/include/vsxu/common/vsx_argvector.h:37,
                 from /usr/include/vsxu/engine/audiovisual/vsx_state_manager.h:27,
                 from visualization/vsxu.cpp:45:
/usr/include/vsxu/common/math/vsx_math.h:53: note: macro "clamp" defined here
   53 | #define clamp(N, L, U) (MAX(MIN((N), (U)), (L)))
      |
In file included from /usr/include/c++/11.1.0/functional:65,
                 from /usr/include/vsxu/common/tools/vsx_thread_pool.h:10,
                 from /usr/include/vsxu/common/filesystem/archive/vsx_filesystem_archive_reader.h:7,
                 from /usr/include/vsxu/common/filesystem/vsx_filesystem.h:9,
                 from /usr/include/vsxu/common/string/vsx_string_helper.h:7,
                 from /usr/include/vsxu/common/vsx_argvector.h:50,
                 from /usr/include/vsxu/engine/audiovisual/vsx_state_manager.h:27,
                 from visualization/vsxu.cpp:45: